package wapidstyle.api.bukkit;

public enum EventType {
	UNDEFINED, BLOCK_PLACE, BLOCK_DESTROY, BLOCK_INTERACT_LEFT, BLOCK_INTERACT_RIGHT,
	ENCHANT_ITEM, ENCHANT_FORBIDDEN_ITEM, ENCHANT_LEVEL_1, ENCHANT_LEVEL_2,
	ENCHANT_LEVEL_3, ITEM_CRAFT, ITEM_DROP, ITEM_BURN, ITEM_PICKUP_HOPPER, ITEM_SMELT,
	ITEM_BREW, ITEM_ENCHANT, PLAYER_MOVE, PLAYER_TURN
}
