cd src
cd main
cd java
cd wapidstyle
mkdir api
cd api
wget https://raw.githubusercontent.com/wapidstyle/wapi/master/src/main/java/wapidstyle/api/Boolean.java 
wget https://raw.githubusercontent.com/wapidstyle/wapi/master/src/main/java/wapidstyle/api/CompiledValue.java
wget https://raw.githubusercontent.com/wapidstyle/wapi/master/src/main/java/wapidstyle/api/BooleanValue.java
wget https://raw.githubusercontent.com/wapidstyle/wapi/master/src/main/java/wapidstyle/api/CompiledValues.java
cd ..
cd ..
mkdir java
cd java
mkdir lang
cd lang
wget https://raw.githubusercontent.com/wapidstyle/wapi/master/src/main/java/java/lang/string.java
cd ..
cd ..
cd ..
cd ..
cd ..